# fly.toml app configuration file generated for water-quality-project-still-sea-4331 on 2024-02-29T17:10:52+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'water-quality-project-still-sea-4331'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
